default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: colony_development

test:
  <<: *default
  database: colony_test

production:
  <<: *default
  database: colony_production
  username: colony
  password: <%= ENV['COLONY_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
